### ISSUE TITLE
Print Matrix, stdout

### ISSUE THREAD

**Issue by Brady-Adcock** [AgileAppstate/javatrix-team-liquid#4]
public void print(int w, int d)

Print the matrix to stdout. Line the elements up in columns with Fortran-like "Fw.d" style format. 

Params:
    - w, column width
    - d, number of digits after decimal

**Comment by Brady-Adcock** [comment]
Fortran-Formating:
https://eml.berkeley.edu/sst/fmttop.html

**Comment by Brady-Adcock** [comment]
write the test for this method as well.

**Comment by jbaldw** [comment]
What should we do in the case that the width is less than the length of the individual matrix values?

**Comment by jbaldw** [comment]
Should the values be right-aligned, left-aligned, or centered?
